Allow all non-copyleft licenses
enarx/enarx-wasmldr pull request #41
Opened 2020-11-10 04:40 UTC by mbestavros

Signed-off-by: Mark Bestavros <mbestavr@redhat.com>

2020-11-11 13:05 UTC, haraldh approved these changes

2020-11-11 21:17 UTC, haraldh requested changes
I don't see any updates to ring here

2020-11-11 21:31 UTC, mbestavros commented
@haraldh Whoops, my mistake. Fixed.

2020-11-11 21:40 UTC, haraldh approved these changes

2020-11-12 18:44 UTC, connorkuehl approved these changes

2020-11-12 18:49 UTC, merged